class col_utils:
    def event_columns():
        return [
            'event_id', 
            'season', 
            'season_week_number', 
            'date', 
            'day_of_week', 
            'home_team', 
            'away_team', 
            'overtime', 
            'is_playoffs', 
            'is_neutral', 
            'is_complete'
        ]

    def col_rename_dict():
        return {
			'Gtm': 'team_game_number',
			'Week': 'season_week_number',
			'Date': 'date',
			'Day': 'day_of_week',
			'Unnamed: 5': 'is_home',
			'Opp': 'opponent',
			'Rslt': 'win',
			'Pts': 'points_scored',
			'PtsO': 'points_allowed',
			'OT': 'overtime',
			'Cmp': 'pass_completions',
			'Att': 'pass_attempts',
			'Cmp%': 'pass_completion_percentage',
			'Yds': 'pass_yds',
			'TD': 'pass_tds',
			'Y/A': 'pass_yards_per_attempt',
			'AY/A': 'pass_adjusted_yards_per_attempt',
			'Rate': 'pass_rating',
			'Sk': 'sacks_allowed',
			'Yds.1': 'sack_yards_lost',
			'Att.1': 'rushing_attempts',
			'Yds.2': 'rushing_yards',
			'TD.1': 'rushing_tds',
			'Y/A.1': 'rushing_yards_per_attempt',
			'Ply': 'offensive_plays',
			'Tot': 'total_yards',
			'Y/P': 'yards_per_play',
			'FGA': 'field_goal_attempts',
			'FGM': 'field_goals_made',
			'XPA': 'extra_point_attempts',
			'XPM': 'extra_points_made',
			'Pnt': 'punts',
			'Yds.3': 'punt_yards',
			'Pass': 'passing_first_downs',
			'Rsh': 'rushing_first_downs',
			'Pen': 'penalty_first_downs',
			'1stD': 'first_downs',
			'3DConv': 'third_down_conversions',
			'3DAtt': 'third_down_attempts',
			'4DConv': 'fourth_down_conversions',
			'4DAtt': 'fourth_down_attempts',
			'Pen.1': 'penalties',
			'Yds.4': 'penalty_yards',
			'FL': 'fumbles_lost',
			'Int': 'interceptions_thrown',
			'TO': 'turnovers',
			'ToP': 'time_of_possession'
		}
    
    def game_data_columns():
        return [
			'event_id',
			'team',
			'date',
			'opponent',
			'is_home',
			'win',
			'points_scored',
			'pass_completions',
			'pass_attempts',
			'pass_completion_percentage',
			'pass_yds',
			'pass_tds',
			'pass_yards_per_attempt',
			'pass_adjusted_yards_per_attempt',
			'pass_rating',
			'sacks_allowed',
			'sack_yards_lost',
			'rushing_attempts',
			'rushing_yards',
			'rushing_tds',
			'rushing_yards_per_attempt',
			'offensive_plays',
			'total_yards',
			'yards_per_play',
			'field_goal_attempts',
			'field_goals_made',
			'extra_point_attempts',
			'extra_points_made',
			'punts',
			'punt_yards',
			'passing_first_downs',
			'rushing_first_downs',
			'penalty_first_downs',
			'first_downs',
			'third_down_conversions',
			'third_down_attempts',
			'fourth_down_conversions',
			'fourth_down_attempts',
			'penalties',
			'penalty_yards',
			'fumbles_lost',
			'interceptions_thrown',
			'turnovers',
			'time_of_possession'
		]